var characters = [
    {
        "name":"Albert Einstein",
        "features":{
            "yearOfBirth":1879,
            "country":"germany",
            "sex":"m",
            "colorOfHair":"white",
            "colorOfEyes":"brown",
            "colorOfMustache":"grey",
            "professions":[
                "physicist"
            ],
            "specialities":[
                "relativity"
            ],
            "awards":7,
            "nobels":1,
            "yearOfDeath":1955
        }
    },
    {
        "name":"Marie Curie",
        "features":{
            "yearOfBirth":1867,
            "country":"poland",
            "sex":"f",
            "colorOfHair":"blonde",
            "colorOfEyes":"brown",
            "colorOfMustache":"no",
            "professions":[
                "physicist",
                "chemist"
            ],
            "specialities":[
                "radio",
                "polonium",
                "x-ray"
            ],
            "awards":2,
            "nobels":2,
            "yearOfDeath":1934
        }
    },
    {
        "name":"Jane Goodall",
        "features":{
            "yearOfBirth":1934,
            "country":"uk",
            "sex":"f",
            "colorOfHair":"white",
            "colorOfEyes":"green",
            "colorOfMustache":"no",
            "professions":[
                "primatologist",
                "ethologist",
                "anthropologist"
            ],
            "specialities":[
                "primate_research"
            ],
            "awards":5,
            "nobels":0,
            "yearOfDeath":null
        }
    },
    {
        "name":"Rosalind Franklin",
        "features":{
            "yearOfBirth":1920,
            "country":"uk",
            "sex":"f",
            "colorOfHair":"brown",
            "colorOfEyes":null,
            "colorOfMustache":"no",
            "professions":[
                "chemist",
                "crystallographer"
            ],
            "specialities":[
                "dna_structure_discovery"
            ],
            "awards":0,
            "nobels":0,
            "yearOfDeath":1958
        }
    },
    {
        "name":"Piero Angela",
        "features":{
            "yearOfBirth":1928,
            "country":"italy",
            "sex":"m",
            "colorOfHair":"white",
            "colorOfEyes":"blue",
            "colorOfMustache":"no",
            "professions":[
                "science_communicator"
            ],
            "specialities":[
                null
            ],
            "awards":1,
            "nobels":0,
            "yearOfDeath":2022
        }
    },
    {
        "name":"Steve Jobs",
        "features":{
            "yearOfBirth":1955,
            "country":"usa",
            "sex":"m",
            "colorOfHair":"grey",
            "colorOfEyes":"brown",
            "colorOfMustache":"white",
            "professions":[
                "entrepreneur"
            ],
            "specialities":[
                "apple_ceo"
            ],
            "awards":4,
            "nobels":0,
            "yearOfDeath":2011
        }
    },
    {
        "name":"Jeff Bezos",
        "features":{
            "yearOfBirth":1964,
            "country":"usa",
            "sex":"m",
            "colorOfHair":"no",
            "colorOfEyes":"brown",
            "colorOfMustache":"no",
            "professions":[
                "entrepreneur",
                "company_manager",
                "company_owner"
            ],
            "specialities":[
                "amazon_owner"
            ],
            "awards":3,
            "nobels":0,
            "yearOfDeath":null
        }
    },
    {
        "name":"Bill Gates",
        "features":{
            "yearOfBirth":1955,
            "country":"usa",
            "sex":"m",
            "colorOfHair":"white",
            "colorOfEyes":"blue",
            "colorOfMustache":"no",
            "professions":[
                "company_owner",
                "company_manager",
                "entrepreneur",
                "informatic"
            ],
            "specialities":[
                "microsoft_founder"
            ],
            "awards":9,
            "nobels":0,
            "yearOfDeath":null
        }
    },
    {
        "name":"Mark Zuckerberg",
        "features":{
            "yearOfBirth":1984,
            "country":"usa",
            "sex":"m",
            "colorOfHair":"blonde",
            "colorOfEyes":"blue",
            "colorOfMustache":"no",
            "professions":[
                "company_owner",
                "company_manager",
                "entrepreneur",
                "informatic"
            ],
            "specialities":[
                "facebook_ceo"
            ],
            "awards":6,
            "nobels":0,
            "yearOfDeath":null
        }
    },
    {
        "name":"Satya Nadella",
        "features":{
            "yearOfBirth":1967,
            "country":"india",
            "sex":"m",
            "colorOfHair":"no",
            "colorOfEyes":"black",
            "colorOfMustache":"no",
            "professions":[
                "company_manager",
                "entrepreneur"
            ],
            "specialities":[
                "microsoft_ceo"
            ],
            "awards":4,
            "nobels":0,
            "yearOfDeath":null
        }
    },
    {
        "name":"Nikola Tesla",
        "features":{
            "yearOfBirth":1856,
            "country":"croatia",
            "sex":"m",
            "colorOfHair":"black",
            "colorOfEyes":null,
            "colorOfMustache":"black",
            "professions":[
                "physicist",
                "engineer",
                "inventor"
            ],
            "specialities":[
                "electrical_system_basis"
            ],
            "awards":4,
            "nobels":0,
            "yearOfDeath":1943
        }
    },
    {
        "name":"Thomas Edison",
        "features":{
            "yearOfBirth":1847,
            "country":"italy",
            "sex":"m",
            "colorOfHair":"white",
            "colorOfEyes":null,
            "colorOfMustache":"no",
            "professions":[
                "inventor",
                "entrepreneur"
            ],
            "specialities":[
                "telegraph_invention"
            ],
            "awards":12,
            "nobels":0,
            "yearOfDeath":1931
        }
    },
    {
        "name":"Henry Ford",
        "features":{
            "yearOfBirth":1863,
            "country":"usa",
            "sex":"m",
            "colorOfHair":"white",
            "colorOfEyes":null,
            "colorOfMustache":"no",
            "professions":[
                "entrepreneur"
            ],
            "specialities":[
                "assembly_line_invention"
            ],
            "awards":3,
            "nobels":0,
            "yearOfDeath":1947
        }
    },
    {
        "name":"Isambard Kingdom Brunel",
        "features":{
            "yearOfBirth":1806,
            "country":"uk",
            "sex":"m",
            "colorOfHair":"black",
            "colorOfEyes":null,
            "colorOfMustache":"black",
            "professions":[
                "engineer"
            ],
            "specialities":[
                "great_eastern_construction"
            ],
            "awards":0,
            "nobels":0,
            "yearOfDeath":1859
        }
    },
    {
        "name":"Elon Musk",
        "features":{
            "yearOfBirth":1971,
            "country":"sudafrica",
            "sex":"m",
            "colorOfHair":"brown",
            "colorOfEyes":"blue",
            "colorOfMustache":"no",
            "professions":[
                "inventor",
                "entrepreneur"
            ],
            "specialities":[
                "spacex_invention"
            ],
            "awards":5,
            "nobels":0,
            "yearOfDeath":null
        }
    },
    {
        "name":"Leonardo da Vinci",
        "features":{
            "yearOfBirth":1452,
            "country":"italy",
            "sex":"m",
            "colorOfHair":"no",
            "colorOfEyes":"black",
            "colorOfMustache":"grey",
            "professions":[
                "inventor",
                "artist"
            ],
            "specialities":[
                "ornithopter_invention"
            ],
            "awards":1,
            "nobels":0,
            "yearOfDeath":1519
        }
    },
    {
        "name":"Vincent Van Gogh",
        "features":{
            "yearOfBirth":1853,
            "country":"netherlands",
            "sex":"m",
            "colorOfHair":"blonde",
            "colorOfEyes":null,
            "colorOfMustache":"blonde",
            "professions":[
                "artist"
            ],
            "specialities":[
                "starry_night_painting"
            ],
            "awards":0,
            "nobels":0,
            "yearOfDeath":1890
        }
    },
    {
        "name":"Frida Kahlo",
        "features":{
            "yearOfBirth":1907,
            "country":"mexico",
            "sex":"f",
            "colorOfHair":"black",
            "colorOfEyes":"black",
            "colorOfMustache":"no",
            "professions":[
                "artist"
            ],
            "specialities":[
                "liberty_expressionist"
            ],
            "awards":2,
            "nobels":0,
            "yearOfDeath":1954
        }
    },
    {
        "name":"Pablo Picasso",
        "features":{
            "yearOfBirth":1881,
            "country":"spain",
            "sex":"m",
            "colorOfHair":"no",
            "colorOfEyes":"brown",
            "colorOfMustache":"no",
            "professions":[
                "artist"
            ],
            "specialities":[
                "blue_and_pink_periods"
            ],
            "awards":4,
            "nobels":0,
            "yearOfDeath":1973
        }
    },
    {
        "name":"Salvador Dali",
        "features":{
            "yearOfBirth":1904,
            "country":"spain",
            "sex":"m",
            "colorOfHair":"black",
            "colorOfEyes":null,
            "colorOfMustache":"black",
            "professions":[
                "artist"
            ],
            "specialities":[
                "surrealism_member"
            ],
            "awards":3,
            "nobels":0,
            "yearOfDeath":1989
        }
    },
    {
        "name":"Isaac Newton",
        "features":{
            "yearOfBirth":1642,
            "country":"uk",
            "sex":"m",
            "colorOfHair":"white",
            "colorOfEyes":"green",
            "colorOfMustache":"no",
            "professions":[
                "physicist",
                "mathematician"
            ],
            "specialities":[
                "gravity_discovery"
            ],
            "awards":0,
            "nobels":0,
            "yearOfDeath":1726
        }
    },
    {
        "name":"Carl Friedrich Gauss",
        "features":{
            "yearOfBirth":1777,
            "country":"germany",
            "sex":"m",
            "colorOfHair":"blonde",
            "colorOfEyes":"blue",
            "colorOfMustache":"no",
            "professions":[
                "mathematician"
            ],
            "specialities":[
                "modular_arithmetic"
            ],
            "awards":2,
            "nobels":0,
            "yearOfDeath":1855
        }
    },
    {
        "name":"Pitagora",
        "features":{
            "yearOfBirth":-575,
            "country":"greece",
            "sex":"m",
            "colorOfHair":"white",
            "colorOfEyes":null,
            "colorOfMustache":"white",
            "professions":[
                "physicist",
                "mathematician"
            ],
            "specialities":[
                "geometric_discoveries"
            ],
            "awards":0,
            "nobels":0,
            "yearOfDeath":-495
        }
    },
    {
        "name":"Archimede",
        "features":{
            "yearOfBirth":-287,
            "country":"italy",
            "sex":"m",
            "colorOfHair":"white",
            "colorOfEyes":null,
            "colorOfMustache":"white",
            "professions":[
                "physicist",
                "mathematician"
            ],
            "specialities":[
                "buoyancy_discovery"
            ],
            "awards":0,
            "nobels":0,
            "yearOfDeath":-212
        }
    },
    {
        "name":"Alan Turing",
        "features":{
            "yearOfBirth":1912,
            "country":"uk",
            "sex":"m",
            "colorOfHair":"brown",
            "colorOfEyes":"blue",
            "colorOfMustache":"no",
            "professions":[
                "physicist",
                "mathematician",
                "informatic"
            ],
            "specialities":[
                "computation_theory"
            ],
            "awards":0,
            "nobels":0,
            "yearOfDeath":1954
        }
    }
]